#!/usr/bin/env python3
"""Prototype: generate function-doc sections from a DuckDB checkout's functions.yaml.

Same rendering, overrides, sorting and URL handling as
generate_sql_function_docs.py — only the data source changes:
descriptions, parameters, aliases and variants come from the
functions.yaml files (see scripts/functions_yaml.py in duckdb/duckdb)
instead of duckdb_functions().
Example results are still computed live via the duckdb Python package.

Usage:
  python3 scripts/generate_sql_function_docs_from_yaml.py --source ⟨duckdb_checkout⟩ [--doc-version current]
"""

import argparse
import glob
import os

import yaml

import generate_sql_function_docs as g

YAML_GLOBS = [
    'src/function/**/functions.yaml',
    'extension/core_functions/**/functions.yaml',
]


def load_yaml_entries(source: str) -> list[dict]:
    entries = []
    for pattern in YAML_GLOBS:
        for path in sorted(
            glob.glob(os.path.join(source, pattern), recursive=True)
        ):
            with open(path) as fh:
                entries += yaml.safe_load(fh)
    return entries


def param_names(parameters) -> list[str]:
    if parameters is None:
        return []
    if isinstance(parameters, str):
        return [p.strip() for p in parameters.split(',') if p.strip()]
    return [p['name'] for p in parameters]


def rows_for(entry: dict, categories: list[str]):
    """DocFunction rows per (variant x category), plus alias rows."""
    name = entry['name']
    aliases = entry.get('aliases', [])
    variants = entry.get('variants') or [entry]
    for variant in variants:
        params = param_names(variant.get('parameters'))
        is_variadic = '...' in params
        params = [p for p in params if p != '...']
        description = variant.get('description', '')
        examples = variant.get('examples') or entry.get('examples') or []
        cats = variant.get('categories') or entry.get('categories') or []
        for category in cats:
            if category not in categories:
                continue
            yield g.DocFunction(
                name=name,
                parameters=params,
                description=description,
                examples=examples,
                category=category,
                alias_of='',
                is_variadic=is_variadic,
                aliases=aliases,
            )
            for alias in aliases:
                yield g.DocFunction(
                    name=alias,
                    parameters=params,
                    description=description,
                    examples=examples,
                    category=category,
                    alias_of=name,
                    is_variadic=is_variadic,
                    aliases=[name] + [a for a in aliases if a != alias],
                )


def get_function_data(entries: list[dict], categories: list[str]):
    rows = []
    for entry in entries:
        rows.extend(rows_for(entry, categories))
    seen = set()
    function_data = []
    for func in rows:
        key = (
            func.name,
            tuple(func.parameters),
            func.description,
            func.category,
            func.alias_of,
        )
        if key in seen:
            continue
        seen.add(key)
        function_data.append(func)
    function_data = g.apply_overrides(function_data, categories)
    function_data = g.sort_function_data(function_data)
    function_data = g.prune_duplicates(function_data)
    for function in function_data:
        g.apply_description_appends(function)
        g.apply_url_conversions(function)
        g.set_canonical_function(function, function_data)
    return function_data


def tolerant_example_rows(func):
    """Fall back to result-less example rows when the installed engine
    does not know a function yet (metadata newer than the engine)."""
    try:
        return _generate_example_rows(func)
    except Exception as error:
        print(f"WARNING: no result for '{func.name}': {error}".split('\n')[0])
        lines = ''
        for idx, example in enumerate(func.examples):
            label = 'Example' if len(func.examples) == 1 else f'Example {idx + 1}'
            lines += f"| **{label}** | `{example}` |\n"
        return lines


_generate_example_rows = g.generate_example_rows
g.generate_example_rows = tolerant_example_rows


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--source', required=True, help='DuckDB checkout with functions.yaml')
    parser.add_argument('--doc-version', default='current')
    args = parser.parse_args()
    entries = load_yaml_entries(args.source)
    block_endline = (
        "<!-- End of section generated by scripts/generate_sql_function_docs.py -->\n"
    )
    for doc_file in g.DOC_FILES:
        doc_file = doc_file.replace(f'docs/{g.DOC_VERSION}/', f'docs/{args.doc_version}/')
        print(f"creating file {doc_file} from YAML ...")
        with open(doc_file) as fh:
            doc_text = fh.read()
        for current_block, startline, categories in g.get_function_blocks(
            doc_text, block_endline
        ):
            function_data = get_function_data(entries, categories)
            updated_block = (
                startline
                + g.generate_docs_table(function_data)
                + g.generate_docs_records(function_data)
                + block_endline
            )
            updated_block = updated_block.replace(
                f'docs/{g.DOC_VERSION}/', f'docs/{args.doc_version}/'
            )
            doc_text = doc_text.replace(current_block, updated_block)
        with open(doc_file, 'w') as fh:
            fh.write(doc_text)


if __name__ == '__main__':
    main()
